### PR TITLE
Updates consistently to go 1.16

### PR DESCRIPTION
**Pull request by codefromthecrypt**
Before, depending on CI, one ran go 1.13 and the other 1.16. This
centralizes to 1.16 in efforts to remove differences between local and
CI runs (as well differences between CI). This is needed anyway for
future change.

Signed-off-by: Adrian Cole <adrian@tetrate.io>

### CODE REVIEW

**Review by mathetake — APPROVED** [review]
LGTM

**Comment by codefromthecrypt** [comment]
the lint failure here is fixed in #132 so I'll move this change into that one

**Comment by codefromthecrypt** [comment]
I'll fix here because migrating off circleci isn't going to be quick

**Comment by codefromthecrypt** [comment]
there's a panic in the output. I'll look into it tomorrow

```
--- FAIL: Test_capture (0.39s)
    --- FAIL: Test_capture/creates_non-empty_access_and_error_log_files (0.39s)
        log_linux_test.go:38: error stating /home/circleci/.getenvoy/debug/1616663621906226331/logs/access.log: stat /home/circleci/.getenvoy/debug/1616663621906226331/logs/access.log: no such file or directory
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x89adb1]

goroutine 53 [running]:
testing.tRunner.func1.2(0x908360, 0xce3ee0)
	/usr/local/go/src/testing/testing.go:1144 +0x332
testing.tRunner.func1(0xc0004ee180)
	/usr/local/go/src/testing/testing.go:1147 +0x4b6
panic(0x908360, 0xce3ee0)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/tetratelabs/getenvoy/pkg/binary/envoy/debug.Test_capture.func1(0xc0004ee180)
	/home/circleci/project/pkg/binary/envoy/debug/log_linux_test.go:40 +0x391
testing.tRunner(0xc0004ee180, 0x9b8378)
	/usr/local/go/src/testing/testing.go:1194 +0xef
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1239 +0x2b3
FAIL	github.com/tetratelabs/getenvoy/pkg/binary/envoy/debug	0.855s
```
